services:
   nginx-demo:
     container_name: testing-nginx-container
     image: testing-nginx
     env_file: 
       - ./environment/dev.env
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 8081:80