services:
   nginx-demo:
     container_name: testing-nginx-container
     image: testing-nginx
     env_file: 
       - environment/${environment}.env
     environment:
       - env=${environment}
     build:
       context: ../
       dockerfile: docker/Dockerfile
     ports:
       - 8081:80