services:
   nginx-demo:
     container_name: testing-nginx-container
     image: testing-nginx
     env_file: 
       - docker/environment/dev.env
     build:
       context: ../
       dockerfile: docker/Dockerfile
     ports:
       - 8081:80